// Repeatable integration checks using the supported Browser skill's existing tab.
// Run against /tests/fixtures/collection-api.html; all transport is isolated there.
import assert from 'node:assert/strict'
const button = (tab, name) => tab.playwright.getByRole('button', { name, exact: true })
const selectNames = ['試験シナリオ', '試験エラー', '応答時間', '確認目的', '取得要否', '取得作業', '確認', '担当者', '作業優先度', '内容充足', '結果・例外']
const label = (tab, name) => tab.playwright.getByRole(name === '閲覧のみ' ? 'checkbox' : selectNames.includes(name) ? 'combobox' : 'textbox', { name, exact: true })
const visible = async (tab, text) => tab.playwright.getByText(text, { exact: true }).waitFor({ state: 'visible' })
const logs = async tab => JSON.parse(await tab.playwright.getByTestId('transport-log').textContent())
const rows = tab => tab.playwright.getByRole('button', { name: /の詳細$/ })
const selectScenario = async (tab, value) => { await label(tab, '試験シナリオ').selectOption(value); await tab.playwright.domSnapshot() }

export async function initializationChecks(tab) {
  await tab.reload()
  await selectScenario(tab, 'uninitialized')
  await button(tab, '資料収集リストを作成').waitFor({ state: 'visible' })
  assert.ok((await tab.playwright.domSnapshot()).includes('3件'))
  assert.ok((await tab.playwright.domSnapshot()).includes('候補資料は自動的に「必要」には設定されません。'))
  assert.equal((await logs(tab)).filter(r => r.method === 'post').length, 0)
  await button(tab, '資料収集リストを作成').click()
  await tab.playwright.getByRole('dialog').waitFor({ state: 'visible' })
  await button(tab, 'キャンセル').click()
  assert.equal((await logs(tab)).filter(r => r.method === 'post').length, 0)
  await label(tab, '応答時間').selectOption('1200')
  await button(tab, '資料収集リストを作成').click()
  await button(tab, '作成する').click()
  assert.equal(await button(tab, '作成中…').isEnabled(), false)
  assert.equal(await button(tab, 'キャンセル').isEnabled(), false)
  await visible(tab, '3件の候補資料を作成しました。')
  await rows(tab).first().waitFor({ state: 'visible' })
  const requests = await logs(tab)
  const postIndex = requests.findIndex(r => r.method === 'post')
  assert.equal(requests.filter(r => r.method === 'post').length, 1)
  assert.equal(requests[postIndex].payload, undefined)
  assert.ok(requests.slice(postIndex + 1).some(r => r.url.endsWith('/initialization-preview')))
  assert.ok(requests.slice(postIndex + 1).some(r => r.url.endsWith('/document-collection')))
  assert.equal(await button(tab, '資料収集リストを作成').count(), 0)
  await label(tab, '応答時間').selectOption('25')
  await selectScenario(tab, 'new')
  await button(tab, '候補を追加').waitFor({ state: 'visible' })
  assert.equal(await rows(tab).count(), 3)
  await button(tab, '候補を追加').click(); await button(tab, '作成する').click()
  await visible(tab, '2件の候補資料を作成しました。')
  await button(tab, '候補を追加').waitFor({ state: 'detached' })
  await selectScenario(tab, 'noop'); await button(tab, '候補を追加').waitFor({ state: 'visible' })
  await button(tab, '候補を追加').click(); await button(tab, '作成する').click()
  await visible(tab, '追加する候補資料はありませんでした。最新の状態を表示します。')
  return ['initial candidate count/wording', 'cancel: no POST', 'confirm: empty POST + duplicate protection', 'success: preview/list refetched', 'no missing action hidden', 'new candidates preserve list', 'no-op truthful feedback']
}

export async function listChecks(tab) {
  await tab.reload(); await rows(tab).first().waitFor({ state: 'visible' })
  assert.equal(await rows(tab).count(), 3)
  const osaka = button(tab, 'D-003 診断書 大阪病院 の詳細')
  const kyoto = button(tab, 'D-003 診断書 京都病院 の詳細')
  assert.equal(await osaka.count(), 1); assert.equal(await kyoto.count(), 1)
  const text = await osaka.innerText()
  for (const value of ['受領済み', '未確認', '不足あり']) assert.ok(text.includes(value))
  assert.ok(!(await osaka.innerText()).includes('保全優先'))
  assert.ok((await kyoto.innerText()).includes('不存在'))
  await button(tab, '通信記録をクリア').click()
  await label(tab, '資料名・コードを検索').fill('D-003')
  await button(tab, '条件をクリア').waitFor({ state: 'visible' })
  // Wait for server-filtered caption rather than sleeping through debounce.
  await tab.playwright.getByText('1–2 / 2件', { exact: true }).waitFor({ state: 'visible' })
  assert.equal(await rows(tab).count(), 2)
  assert.ok((await logs(tab)).some(r => r.params?.search === 'D-003' && r.params.page === 1))
  assert.ok((await tab.playwright.getByLabel('資料収集サマリー').innerText()).includes('3'))
  await button(tab, '絞り込み').click(); await tab.playwright.domSnapshot()
  await label(tab, '確認目的').selectOption('W3')
  await label(tab, '取得要否').selectOption('required')
  await label(tab, '取得作業').selectOption('received')
  await label(tab, '確認').selectOption('unreviewed')
  await label(tab, '担当者').selectOption('1')
  await tab.playwright.getByText('1–1 / 1件', { exact: true }).waitFor({ state: 'visible' })
  const latest = (await logs(tab)).filter(r => r.url.endsWith('/document-collection')).at(-1).params
  assert.equal(latest.purpose, 'W3'); assert.equal(latest.necessity_status, 'required'); assert.equal(latest.collection_status, 'received'); assert.equal(latest.review_status, 'unreviewed'); assert.equal(latest.assignee_id, 1)
  await button(tab, '条件をクリア').click()
  await label(tab, '資料名・コードを検索').fill('no-such-document')
  await visible(tab, '該当する資料がありません')
  await selectScenario(tab, 'paginated'); await button(tab, '次へ').waitFor({ state: 'visible' })
  await button(tab, '次へ').click(); await visible(tab, '26–31 / 31件')
  assert.equal(await rows(tab).count(), 6)
  await label(tab, '資料名・コードを検索').fill('D-003')
  await visible(tab, '1–21 / 21件')
  assert.equal((await logs(tab)).filter(r => r.url.endsWith('/document-collection')).at(-1).params.page, 1)
  return ['unique item IDs + multi-purpose', 'independent axes/result/preservation', 'server search and case summary', 'five-axis query mapping', 'empty result', 'pagination + reset page']
}

export async function inspectorChecks(tab) {
  await tab.reload(); await rows(tab).first().waitFor({ state: 'visible' })
  await label(tab, '応答時間').selectOption('1200')
  await button(tab, 'D-003 診断書 大阪病院 の詳細').click()
  await visible(tab, '資料の詳細を読み込み中…')
  assert.equal(await label(tab, '資料名・コードを検索').isEnabled(), true)
  await label(tab, '取得先').waitFor({ state: 'visible' })
  await label(tab, '応答時間').selectOption('25')
  assert.equal(await button(tab, '保存').isEnabled(), false)
  for (const name of ['取得先', '取得方法', '対象者', '対象期間・開始', '対象期間・終了', '対象範囲', '担当者', '依頼日時', '回答期限', '作業優先度', '保全理由', '取得作業', '内容充足', '確認', '結果・例外']) assert.equal(await label(tab, name).count(), 1)
  assert.equal(await tab.playwright.getByRole('link', { name: '資料リンクを開く' }).getAttribute('href'), 'https://example.test/document')
  await button(tab, '不要').click(); await tab.playwright.getByRole('textbox', { name: /^判断理由/ }).fill('   ')
  await button(tab, '保存').click(); await visible(tab, '不要と判断した理由を入力してください。')
  assert.equal((await logs(tab)).filter(r => r.method === 'patch').length, 0)
  await button(tab, 'キャンセル').click()
  await label(tab, '試験エラー').selectOption('patch:422')
  await label(tab, '取得先').fill('試験病院・更新')
  await button(tab, '保存').click(); await tab.playwright.getByText('取得先の入力を確認してください。', { exact: true }).first().waitFor({ state: 'visible' })
  assert.equal(await button(tab, '詳細を閉じる').count(), 1)
  assert.equal(await tab.playwright.getByRole('textbox', { name: /^取得先/ }).getAttribute('aria-invalid'), 'true')
  await label(tab, '試験エラー').selectOption('')
  await button(tab, '通信記録をクリア').click()
  await button(tab, '保存').click(); await visible(tab, '保存しました。')
  const requests = await logs(tab)
  assert.deepEqual(requests.find(r => r.method === 'patch').payload, { collection_source: '試験病院・更新' })
  assert.ok(requests.some(r => r.method === 'get' && r.url.endsWith('/201')))
  assert.ok(requests.some(r => r.method === 'get' && r.url.endsWith('/document-collection')))
  await button(tab, '保存').waitFor({ state: 'visible' })
  await button(tab, '詳細を閉じる').click()
  await label(tab, '閲覧のみ').check()
  await button(tab, 'D-003 診断書 試験病院・更新 の詳細').waitFor({ state: 'visible' })
  await button(tab, 'D-003 診断書 試験病院・更新 の詳細').click()
  await label(tab, '取得先').waitFor({ state: 'visible' })
  assert.equal(await label(tab, '取得先').isEnabled(), false)
  assert.equal(await button(tab, '保存').isEnabled(), false)
  return ['detail fetch and local loading', '18 editable fields and readonly snapshots', 'received metadata/link', 'not_required validation before PATCH', '422 retains draft/inspector', 'changed-only PATCH + refresh detail/list', 'read-only authorization']
}

export async function errorChecks(tab) {
  await tab.reload()
  const results = []
  for (const [error, expected] of [['preview:401', 'ログインの有効期限が切れています。再度ログインしてください。'], ['preview:403', 'この操作を行う権限がありません。管理者に確認してください。'], ['preview:404', '案件または資料が見つかりません。一覧を再読み込みしてください。'], ['preview:500', '資料収集データを取得・保存できませんでした。接続を確認して再試行してください。'], ['preview:network', '資料収集データを取得・保存できませんでした。接続を確認して再試行してください。']]) {
    await label(tab, '試験エラー').selectOption(error)
    await selectScenario(tab, 'uninitialized')
    await visible(tab, expected)
    assert.ok(!(await tab.playwright.domSnapshot()).includes('Never display this raw'))
    results.push(error)
  }
  await label(tab, '試験エラー').selectOption('')
  await selectScenario(tab, 'no-rules'); await tab.playwright.getByText('この事件類型には資料収集ルールが登録されていません。', { exact: true }).first().waitFor({ state: 'visible' })
  assert.equal(await button(tab, '資料収集リストを作成').count(), 0)
  await selectScenario(tab, 'missing-type'); await visible(tab, '事件類型が設定されていません。')
  assert.equal(await button(tab, '資料収集リストを作成').count(), 0)
  await selectScenario(tab, 'warnings'); await visible(tab, '旧書類データが含まれています。自動移行は行いません。')
  await rows(tab).first().waitFor({ state: 'visible' }); assert.equal(await rows(tab).count(), 3)
  return [...results, 'no rules', 'missing case type', 'coexistence warnings keep collection']
}

export async function recoveryChecks(tab) {
  await tab.reload(); await rows(tab).first().waitFor({ state: 'visible' })
  await label(tab, '試験エラー').selectOption('detail:404')
  await button(tab, 'D-003 診断書 大阪病院 の詳細').click()
  await visible(tab, '案件または資料が見つかりません。一覧を再読み込みしてください。')
  assert.equal(await rows(tab).count(), 3)
  await button(tab, '詳細を閉じる').click()
  await label(tab, '試験エラー').selectOption('detail:500')
  await button(tab, 'D-003 診断書 大阪病院 の詳細').click()
  await button(tab, '再試行').waitFor({ state: 'visible' })
  await label(tab, '試験エラー').selectOption(''); await button(tab, '再試行').click()
  await label(tab, '取得先').waitFor({ state: 'visible' })
  await label(tab, '試験エラー').selectOption('patch:500')
  await label(tab, '取得方法').fill('試験用の取得方法')
  await button(tab, '保存').click(); await button(tab, '再試行').waitFor({ state: 'visible' })
  assert.equal(await label(tab, '取得方法').textContent(), '試験用の取得方法')
  await label(tab, '試験エラー').selectOption(''); await button(tab, '再試行').click()
  await visible(tab, '保存しました。'); await button(tab, '保存').waitFor({ state: 'visible' })
  await button(tab, '詳細を閉じる').click()
  await label(tab, '試験エラー').selectOption('list:500')
  await label(tab, '資料名・コードを検索').fill('D-003')
  await button(tab, '再試行').waitFor({ state: 'visible' })
  await label(tab, '試験エラー').selectOption(''); await button(tab, '再試行').click()
  await rows(tab).first().waitFor({ state: 'visible' }); assert.equal(await rows(tab).count(), 2)
  await selectScenario(tab, 'uninitialized')
  await button(tab, '資料収集リストを作成').waitFor({ state: 'visible' })
  await label(tab, '試験エラー').selectOption('initialize:500')
  await button(tab, '資料収集リストを作成').click(); await button(tab, '作成する').click()
  await button(tab, '再試行').waitFor({ state: 'visible' })
  assert.equal(await tab.playwright.getByRole('dialog').count(), 1)
  await button(tab, 'キャンセル').click()
  await label(tab, '閲覧のみ').check()
  await visible(tab, 'リスト作成は編集権限のある担当者に依頼してください。')
  assert.equal(await button(tab, '資料収集リストを作成').count(), 0)
  return ['detail 404 retains list', 'detail 500 retry', 'PATCH 500 retains draft/retry', 'list 500 retry', 'initialize failure keeps confirmation', 'read-only initialization']
}

export async function fieldChecks(tab) {
  await tab.reload(); await rows(tab).first().waitFor({ state: 'visible' })
  await button(tab, 'D-003 診断書 大阪病院 の詳細').click()
  await label(tab, '取得先').waitFor({ state: 'visible' })
  await button(tab, '通信記録をクリア').click()
  await label(tab, '対象者').fill('変更対象')
  await label(tab, '取得先').fill('変更先')
  await label(tab, '取得方法').fill('変更方法')
  await label(tab, '対象範囲').fill('変更範囲')
  await label(tab, '担当者').selectOption('2')
  await label(tab, '作業優先度').selectOption('normal')
  await tab.playwright.getByRole('checkbox', { name: '保全優先', exact: true }).check()
  await label(tab, '保全理由').fill('保存期間を確認')
  await button(tab, '不要').click()
  await tab.playwright.getByRole('textbox', { name: /^判断理由/ }).fill('本件では対象外')
  await label(tab, '取得作業').selectOption('closed')
  await label(tab, '内容充足').selectOption('satisfied_by_alternative')
  await label(tab, '確認').selectOption('reviewing')
  await label(tab, '結果・例外').selectOption('other')
  await button(tab, '保存').click(); await visible(tab, '保存しました。')
  const payload = (await logs(tab)).find(r => r.method === 'patch').payload
  // Native date/datetime serialization and paired-date validation are covered in node tests;
  // this browser transport cannot reliably commit native segmented date controls.
  assert.equal(Object.keys(payload).length, 14)
  assert.equal(payload.collection_source, '変更先'); assert.equal(payload.collection_method, '変更方法')
  assert.equal(payload.assigned_employee_id, 2); assert.equal(payload.preservation_priority, true); assert.equal(payload.collection_priority, 'normal')
  assert.equal(payload.necessity_status, 'not_required'); assert.equal(payload.collection_status, 'closed'); assert.equal(payload.review_status, 'reviewing'); assert.equal(payload.fulfillment_status, 'satisfied_by_alternative'); assert.equal(payload.collection_result, 'other')
  assert.ok(!('requested_at' in payload)); assert.ok(!('response_deadline' in payload))
  await button(tab, '保存').waitFor({ state: 'visible' }); await button(tab, '詳細を閉じる').click()
  await button(tab, '絞り込み').click(); await tab.playwright.domSnapshot()
  await label(tab, '取得先').fill('変更先'); await label(tab, '資料名・コードを検索').click()
  await visible(tab, '1–1 / 1件')
  const query = (await logs(tab)).filter(r => r.url.endsWith('/document-collection')).at(-1).params
  assert.equal(query.source, '変更先')
  return ['14 non-date editor fields PATCH independently', 'unchanged dates excluded from PATCH', 'source filter parameter mapping']
}
