// Read-only design fixture, copied from the audited Phase 1C JSON (v1.0, 2026-08-30).
// Not a generator or live master import. See docs/frontend/DOCUMENT_COLLECTION_MOCKUP.md.
import type { OfficialCandidate } from './types'

export const officialCandidates: OfficialCandidate[] = [
  {"caseType":"労災","code":"C-001","title":"委任契約書","purposes":["COMMON"],"condition":null,"source":"事務所で作成／依頼者から回収","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"交通事故","code":"C-001","title":"委任契約書","purposes":["COMMON"],"condition":null,"source":"事務所で作成／依頼者から回収","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"労災","code":"C-002","title":"委任状（民事）","purposes":["COMMON","W4"],"condition":"民事交渉・訴訟等の権限を確認する。提出先・手続ごとの使用可否を確認する。\n共通項目を参照。個別の取得手続で使えるか確認する。","source":"事務所で作成／依頼者から回収","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"交通事故","code":"C-002","title":"委任状（民事）","purposes":["COMMON","T5"],"condition":"民事交渉・訴訟等の権限を確認する。提出先・手続ごとの使用可否を確認する。\n共通項目を参照し、個別の取得手続で使えるか確認する。","source":"事務所で作成／依頼者から回収","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"労災","code":"C-003","title":"本人確認資料","purposes":["COMMON"],"condition":"氏名・住所等を確認する。在留カード・旅券等は必要な範囲で収集する。","source":"依頼者","target":"依頼者","scope":null,"version":1,"preservation":false},
  {"caseType":"交通事故","code":"C-003","title":"本人確認資料","purposes":["COMMON"],"condition":"氏名・住所等を確認する。在留カード・旅券等は必要な範囲で収集する。","source":"依頼者","target":"依頼者","scope":null,"version":1,"preservation":false},
  {"caseType":"労災","code":"C-004","title":"既存の事件資料一式","purposes":["COMMON"],"condition":null,"source":"依頼者","target":null,"scope":"資料ごとに分割し、D-016・D-017等との重複を確認する。","version":1,"preservation":false},
  {"caseType":"交通事故","code":"C-004","title":"既存の事件資料一式","purposes":["COMMON"],"condition":null,"source":"依頼者","target":null,"scope":"資料ごとに分割し、D-016・D-017等との重複を確認する。","version":1,"preservation":false},
  {"caseType":"労災","code":"W-101","title":"雇用契約書","purposes":["W1"],"condition":null,"source":"本人・会社","target":null,"scope":"事故時点で適用される版を特定する。","version":1,"preservation":false},
  {"caseType":"労災","code":"W-102","title":"労働条件通知書","purposes":["W1"],"condition":null,"source":"本人・会社","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"労災","code":"W-103","title":"賃金台帳","purposes":["W1","W3"],"condition":null,"source":"会社・本人保管分","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"労災","code":"W-104","title":"タイムカード・出勤簿・勤怠データ","purposes":["W1"],"condition":null,"source":"本人・会社","target":null,"scope":"事故前後の就労・休業状況。対象期間を指定する。","version":1,"preservation":false},
  {"caseType":"労災","code":"W-105","title":"技能実習計画・認定通知・変更関係書類","purposes":["W1"],"condition":"技能実習事件の場合。認定された業務と実際の作業を比較する。","source":"本人・会社・監理団体","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"労災","code":"W-106","title":"就業規則・賃金規程","purposes":["W1"],"condition":null,"source":"会社・本人保管分","target":null,"scope":"事故時点の適用版を取得する。","version":1,"preservation":false},
  {"caseType":"労災","code":"W-201","title":"監督復命書・添付資料","purposes":["W2"],"condition":"事故に関連する監督・指摘事項を確認する。本人情報該当性・開示範囲を確認する。","source":"管轄労働局等への開示請求","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"労災","code":"W-202","title":"災害調査復命書・添付資料","purposes":["W2"],"condition":"事故原因・災害調査結果を確認する。すべての事故で作成されるわけではない。","source":"管轄労働局等への開示請求","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"労災","code":"W-203","title":"安全衛生教育記録","purposes":["W2"],"condition":null,"source":"会社","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"労災","code":"W-204","title":"技能研修・技能講習・特別教育の記録、修了証","purposes":["W2"],"condition":"作業に必要な教育・資格を確認する。研修・技能講習・特別教育は混同せず内訳を特定する。","source":"本人・会社・講習機関","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"労災","code":"W-205","title":"機械の取扱説明書","purposes":["W2"],"condition":null,"source":"会社・メーカー","target":null,"scope":"機種・型式・版を特定する。","version":1,"preservation":false},
  {"caseType":"労災","code":"W-206","title":"技能実習日誌","purposes":["W2"],"condition":"技能実習事件の場合。実際の作業・指導状況を確認する。","source":"会社","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"労災","code":"W-207","title":"認定計画の履行状況に係る管理簿","purposes":["W2"],"condition":"技能実習事件の場合。技能実習計画の履行状況を確認する。","source":"会社","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"労災","code":"W-208","title":"監理団体側の技能実習関連管理簿","purposes":["W2"],"condition":"監理体制等が関係する場合。実習実施者の管理簿等、必要な帳簿名を具体化する。","source":"監理団体","target":null,"scope":"実習実施者の管理簿等、必要な帳簿名を具体化する。","version":1,"preservation":false},
  {"caseType":"労災","code":"W-209","title":"業務別の労働安全衛生措置の実施記録","purposes":["W2"],"condition":"作業計画、点検、作業指揮、保護具等。作業内容と適用法令を弁護士が確認し、収集する記録を特定する。","source":"会社","target":null,"scope":"作業計画、点検、作業指揮、保護具等。収集する記録を特定する。","version":1,"preservation":false},
  {"caseType":"労災","code":"W-210","title":"現場・機械・負傷部位の写真、動画、防犯カメラ映像","purposes":["W2"],"condition":null,"source":"本人・会社・現場管理者","target":null,"scope":"保存期間・上書き予定を確認する。","version":1,"preservation":true},
  {"caseType":"労災","code":"W-211","title":"事故報告書","purposes":["W2"],"condition":null,"source":"会社・本人保管分","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"労災","code":"W-212","title":"労働者死傷病報告","purposes":["W2"],"condition":"行政機関への報告内容を確認する。存在・取得可能性を確認する。","source":"会社・開示対象となる行政機関","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"労災","code":"W-213","title":"再発防止資料","purposes":["W2"],"condition":null,"source":"会社","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"労災","code":"W-214","title":"機械の点検・修理、安全装置の設置・変更記録","purposes":["W2"],"condition":null,"source":"会社・保守業者","target":null,"scope":"事故前後の記録を区別する。","version":1,"preservation":false},
  {"caseType":"労災","code":"W-215","title":"作業指示書・マニュアル・連絡メッセージ","purposes":["W2"],"condition":null,"source":"本人・会社・関係者","target":null,"scope":"事故前後の経過。","version":1,"preservation":false},
  {"caseType":"労災","code":"W-216","title":"目撃者の連絡先・説明記録","purposes":["W2"],"condition":"事故態様の裏付け。接触方針を確認し、説明者・聴取日・原文を記録する。","source":"本人・関係者","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"労災","code":"W-217","title":"監理団体の監査・訪問指導・相談対応記録","purposes":["W2"],"condition":"監理団体の関与・事前把握状況が関係する場合に取得する。","source":"監理団体","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"労災","code":"D-001","title":"給与明細","purposes":["W3","W1"],"condition":null,"source":"本人・会社","target":null,"scope":"少なくとも事故前3か月分。必要に応じ事故前1年程度・事故後にも範囲を拡張する。","version":1,"preservation":false},
  {"caseType":"労災","code":"D-002","title":"源泉徴収票・賞与明細等の年収資料","purposes":["W3"],"condition":null,"source":"本人・会社","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"労災","code":"D-003","title":"診断書","purposes":["W3"],"condition":null,"source":"医療機関・本人保管分","target":null,"scope":"複数の医療機関・作成日を区別する。","version":1,"preservation":false},
  {"caseType":"労災","code":"D-004","title":"カルテ・診療記録一式","purposes":["W3"],"condition":null,"source":"各医療機関","target":null,"scope":"手術・検査・リハビリ記録等の内訳と対象期間を指定する。","version":1,"preservation":false},
  {"caseType":"労災","code":"D-005","title":"画像資料・検査結果","purposes":["W3"],"condition":null,"source":"各医療機関","target":null,"scope":"画像データ本体と読影・検査報告を区別する。","version":1,"preservation":false},
  {"caseType":"労災","code":"D-006","title":"休業証明・休業損害証明書","purposes":["W3"],"condition":null,"source":"本人・会社","target":null,"scope":"休業期間。手続に合った様式を指定する。","version":1,"preservation":false},
  {"caseType":"労災","code":"D-007","title":"事故後の勤怠・給与資料、復職記録","purposes":["W3"],"condition":null,"source":"本人・会社","target":null,"scope":"事故後の減収・復職後の支障。","version":1,"preservation":false},
  {"caseType":"労災","code":"D-008","title":"治療費・通院交通費・付添費・装具等の領収書・明細","purposes":["W3"],"condition":null,"source":"本人・医療機関等","target":null,"scope":"対象期間・支出目的。費用種類ごとに分割する。","version":1,"preservation":false},
  {"caseType":"労災","code":"W-301","title":"労災保険給付支給請求書・添付書類","purposes":["W3"],"condition":null,"source":"本人・会社・労基署関係資料","target":null,"scope":"給付種類ごとに管理する。","version":1,"preservation":false},
  {"caseType":"労災","code":"W-302","title":"労災給付認定に関する調査復命書・添付資料","purposes":["W3"],"condition":null,"source":"管轄労働局等への開示請求","target":null,"scope":"対象給付・処分を特定する。","version":1,"preservation":false},
  {"caseType":"労災","code":"W-303","title":"支給・不支給決定通知","purposes":["W3"],"condition":null,"source":"本人・関係行政機関","target":null,"scope":"決定日・対象給付。","version":1,"preservation":false},
  {"caseType":"労災","code":"W-304","title":"支払振込通知・支払証明","purposes":["W3"],"condition":null,"source":"本人・関係行政機関","target":null,"scope":"給付種類・対象期間。","version":1,"preservation":false},
  {"caseType":"労災","code":"D-016","title":"既払金一覧・支払記録","purposes":["W3"],"condition":null,"source":"本人・会社・保険会社等","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"労災","code":"D-017","title":"既存の合意書・免責証書・示談書・交渉記録","purposes":["W3"],"condition":null,"source":"本人・会社・保険会社等","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"労災","code":"D-009","title":"後遺障害診断書","purposes":["W3"],"condition":"後遺障害が問題となる場合。症状固定等の判断・作成依頼時期を弁護士が確認する。","source":"医療機関","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"労災","code":"D-010","title":"就労・生活上の支障の記録","purposes":["W3"],"condition":"後遺障害等が問題となる場合。事故前後の差、記録者、日付を確認する。","source":"本人・家族・会社等","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"労災","code":"D-011","title":"死亡診断書・死体検案書","purposes":["W3"],"condition":"死亡事件の場合。死亡原因等を確認する。","source":"医療機関・遺族","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"労災","code":"D-012","title":"戸籍関係資料","purposes":["W3"],"condition":"死亡事件等で相続・身分関係の確認が必要な場合。対象者・範囲を限定する。","source":"遺族・関係行政機関","target":"身分・相続関係の確認対象者（範囲は個別に確認）","scope":"対象者・範囲を限定する。","version":1,"preservation":false},
  {"caseType":"労災","code":"D-013","title":"扶養・生計関係資料","purposes":["W3"],"condition":"扶養・生計関係が損害等の検討に必要な場合。","source":"本人・遺族・会社等","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"労災","code":"D-014","title":"葬儀費用資料","purposes":["W3"],"condition":"死亡事件の場合。費目・支払額・支払者を確認する。","source":"遺族・葬儀業者等","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"労災","code":"A-001","title":"委任状（保有個人情報開示請求）","purposes":["W4"],"condition":"労働局等への本人情報の開示請求。提出先様式・権限を確認する。","source":"依頼者","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"労災","code":"W-401","title":"委任状（労災給付処分への審査請求）","purposes":["W4"],"condition":"当該審査請求を行う場合。対象処分・代理権・手続を確認する。","source":"依頼者","target":null,"scope":"対象処分・代理権・手続を確認する。","version":1,"preservation":false},
  {"caseType":"労災","code":"A-002","title":"委任状（不開示決定等への審査請求）","purposes":["W4"],"condition":"開示手続で不服申立てを行う場合。W-401と混同しない。","source":"依頼者","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"労災","code":"A-003","title":"同意書・委任状（医療機関宛て）","purposes":["W4"],"condition":"診療情報の取得。医療機関、対象期間、同意範囲を確認する。","source":"依頼者等","target":null,"scope":"医療機関、対象期間、同意範囲を確認する。","version":1,"preservation":false},
  {"caseType":"労災","code":"A-004","title":"各機関の開示請求書・申込書、本人・代理人確認資料","purposes":["W4"],"condition":"委任状とは別に提出先が要求するものを準備する。不要な個人情報を収集しない。","source":"事務所・依頼者等","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"労災","code":"W-501","title":"委任状（労基署への告訴等）","purposes":["W5"],"condition":"弁護士の方針決定後に開始する手続。弁護士による承認前に提出しない。","source":"事務所で作成／依頼者から回収","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"労災","code":"W-502","title":"委任状（警察署への告訴等）","purposes":["W5"],"condition":"弁護士の方針決定後に開始する手続。弁護士による承認前に提出しない。","source":"事務所で作成／依頼者から回収","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"労災","code":"W-503","title":"告訴状・告発状、事実経過表、証拠一覧、提出用証拠写し","purposes":["W5"],"condition":"弁護士の方針決定後に開始する手続。弁護士による承認前に提出しない。","source":"事務所で作成","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"交通事故","code":"T-101","title":"交通事故証明書","purposes":["T1"],"condition":"事故の発生、当事者、取扱警察署等を確認する。代理申請の必要書類を確認する。","source":"自動車安全運転センター","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"交通事故","code":"T-102","title":"事故状況図・本人の事故経過説明","purposes":["T1"],"condition":null,"source":"本人","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"交通事故","code":"T-103","title":"ドライブレコーダー・防犯カメラ映像","purposes":["T1"],"condition":"事故態様を確認する。保全優先。外部接触・取得方針の承認が必要。","source":"本人・相手方・周辺施設等","target":null,"scope":null,"version":1,"preservation":true},
  {"caseType":"交通事故","code":"T-104","title":"現場・車両損傷・道路・信号・標識等の写真","purposes":["T1"],"condition":null,"source":"本人・保険会社等","target":null,"scope":"撮影時点と事故時点の相違を記録する。","version":1,"preservation":true},
  {"caseType":"交通事故","code":"T-105","title":"目撃者の連絡先・説明、事故直後のメッセージ","purposes":["T1"],"condition":"事故態様の裏付け。聴取・接触方針を確認する。","source":"本人・関係者","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"交通事故","code":"T-106","title":"実況見分調書等の刑事記録","purposes":["T1"],"condition":"手続段階、記録の種類、処分状況等に応じて取得方法・範囲を確認する。","source":"検察庁・裁判所等","target":null,"scope":"手続段階、記録の種類、処分状況等に応じて取得方法・範囲を確認する。","version":1,"preservation":false},
  {"caseType":"交通事故","code":"T-107","title":"相手方・保険会社の事故状況説明、過失割合の主張・根拠","purposes":["T1"],"condition":null,"source":"本人・保険会社等","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"交通事故","code":"D-003","title":"診断書","purposes":["T2"],"condition":"人身事故の場合（T2. 人身損害の確認）。","source":"医療機関・本人保管分","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"交通事故","code":"T-201","title":"診療報酬明細書","purposes":["T2"],"condition":"人身事故の場合（T2. 人身損害の確認）。","source":"医療機関・本人・保険会社等","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"交通事故","code":"D-004","title":"カルテ・診療記録一式","purposes":["T2"],"condition":"人身事故の場合（T2. 人身損害の確認）。","source":"各医療機関","target":null,"scope":"医療機関・期間・必要な内訳を指定する。","version":1,"preservation":false},
  {"caseType":"交通事故","code":"D-005","title":"画像資料・検査結果","purposes":["T2"],"condition":"人身事故の場合（T2. 人身損害の確認）。","source":"各医療機関","target":null,"scope":"画像本体と報告を区別する。","version":1,"preservation":false},
  {"caseType":"交通事故","code":"D-008","title":"治療費・通院交通費・付添費・装具等の領収書・明細","purposes":["T2"],"condition":"人身事故の場合（T2. 人身損害の確認）。","source":"本人・医療機関等","target":null,"scope":"費用の種類、支払者、期間、必要性を確認する。","version":1,"preservation":false},
  {"caseType":"交通事故","code":"D-006","title":"休業証明・休業損害証明書","purposes":["T2"],"condition":"人身事故の場合（T2. 人身損害の確認）。\n休業・減収がある場合。","source":"本人・会社","target":null,"scope":"対象期間と証明内容を確認する。","version":1,"preservation":false},
  {"caseType":"交通事故","code":"D-001","title":"給与明細","purposes":["T2"],"condition":"人身事故の場合（T2. 人身損害の確認）。\n給与所得者の場合。","source":"本人・会社","target":"給与所得者","scope":"事故前収入・事故後減収等。対象期間は弁護士が指定する。","version":1,"preservation":false},
  {"caseType":"交通事故","code":"D-002","title":"源泉徴収票・賞与明細等の年収資料","purposes":["T2"],"condition":"人身事故の場合（T2. 人身損害の確認）。\n給与所得者の場合。","source":"本人・会社","target":"給与所得者","scope":null,"version":1,"preservation":false},
  {"caseType":"交通事故","code":"D-007","title":"事故後の勤怠・給与資料、復職記録","purposes":["T2"],"condition":"人身事故の場合（T2. 人身損害の確認）。","source":"本人・会社","target":null,"scope":"事故後の就労状況・減収。","version":1,"preservation":false},
  {"caseType":"交通事故","code":"T-202","title":"確定申告書・帳簿等の収入・減収資料","purposes":["T2"],"condition":"人身事故の場合（T2. 人身損害の確認）。\n自営業者等の場合。事故前所得・事故後減収を確認する。","source":"本人・税務関係資料保管者","target":"自営業者等","scope":null,"version":1,"preservation":false},
  {"caseType":"交通事故","code":"T-203","title":"家族構成・家事分担・事故後の支障の資料","purposes":["T2"],"condition":"人身事故の場合（T2. 人身損害の確認）。\n家事従事者の損害を検討する場合。","source":"本人・家族","target":"家事従事者","scope":null,"version":1,"preservation":false},
  {"caseType":"交通事故","code":"D-009","title":"後遺障害診断書","purposes":["T2"],"condition":"人身事故の場合（T2. 人身損害の確認）。\n後遺障害が問題となる場合。作成依頼時期を確認する。","source":"医療機関","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"交通事故","code":"T-204","title":"後遺障害等級認定結果・理由","purposes":["T2"],"condition":"人身事故の場合（T2. 人身損害の確認）。\n認定済みの場合。対象手続・認定内容・理由を確認する。","source":"本人・保険会社等","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"交通事故","code":"D-010","title":"就労・生活上の支障の記録","purposes":["T2"],"condition":"人身事故の場合（T2. 人身損害の確認）。\n事故前後の差、記録者、日付を確認する。","source":"本人・家族・会社等","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"交通事故","code":"D-011","title":"死亡診断書・死体検案書","purposes":["T2"],"condition":"人身事故の場合（T2. 人身損害の確認）。\n死亡事故の場合。","source":"医療機関・遺族","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"交通事故","code":"D-012","title":"戸籍関係資料","purposes":["T2"],"condition":"人身事故の場合（T2. 人身損害の確認）。\n死亡事故等で身分・相続関係の確認が必要な場合。","source":"遺族・関係行政機関","target":"身分・相続関係の確認対象者（範囲は個別に確認）","scope":null,"version":1,"preservation":false},
  {"caseType":"交通事故","code":"D-013","title":"扶養・生計関係資料","purposes":["T2"],"condition":"人身事故の場合（T2. 人身損害の確認）。\n扶養・生計関係が損害等の検討に必要な場合。","source":"本人・遺族・会社等","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"交通事故","code":"D-014","title":"葬儀費用資料","purposes":["T2"],"condition":"人身事故の場合（T2. 人身損害の確認）。\n死亡事故の場合。","source":"遺族・葬儀業者等","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"交通事故","code":"T-301","title":"車検証等の車両・所有者確認資料","purposes":["T3"],"condition":"物損がある場合（T3. 物的損害の確認）。","source":"本人・所有者等","target":"車両の所有者・使用者","scope":null,"version":1,"preservation":false},
  {"caseType":"交通事故","code":"T-302","title":"修理見積書・修理明細・請求書","purposes":["T3"],"condition":"物損がある場合（T3. 物的損害の確認）。","source":"本人・修理業者・保険会社等","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"交通事故","code":"T-303","title":"車両の事故前価値を確認する資料","purposes":["T3"],"condition":"物損がある場合（T3. 物的損害の確認）。\n車両価値が問題となる場合。年式・走行距離・状態等を確認する。","source":"本人・販売店・査定資料等","target":null,"scope":"年式・走行距離・状態等を確認する。","version":1,"preservation":false},
  {"caseType":"交通事故","code":"T-304","title":"レッカー・保管・代車等の費用・利用期間・必要性の資料","purposes":["T3"],"condition":"物損がある場合（T3. 物的損害の確認）。","source":"本人・各事業者等","target":null,"scope":"費用・利用期間・必要性。費目ごとに分割する。","version":1,"preservation":false},
  {"caseType":"交通事故","code":"T-305","title":"携行品等の写真・購入・修理資料","purposes":["T3"],"condition":"物損がある場合（T3. 物的損害の確認）。\n車両以外の物損がある場合。物品ごとに管理する。","source":"本人・購入先・修理業者等","target":null,"scope":"物品ごとに管理する。","version":1,"preservation":false},
  {"caseType":"交通事故","code":"T-401","title":"保険証券・契約内容・特約の確認資料","purposes":["T4"],"condition":null,"source":"本人・保険会社等","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"交通事故","code":"T-402","title":"自賠責請求書類・支払通知","purposes":["T4"],"condition":null,"source":"本人・保険会社等","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"交通事故","code":"T-403","title":"賠償提示書・計算明細","purposes":["T4"],"condition":null,"source":"本人・相手方保険会社等","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"交通事故","code":"D-016","title":"既払金一覧・支払記録","purposes":["T4"],"condition":null,"source":"本人・会社・保険会社等","target":null,"scope":"対象期間。","version":1,"preservation":false},
  {"caseType":"交通事故","code":"D-017","title":"既存の合意書・免責証書・示談書・交渉記録","purposes":["T4"],"condition":null,"source":"本人・会社・保険会社等","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"交通事故","code":"T-404","title":"第三者行為災害関係資料","purposes":["T4"],"condition":"業務中・通勤中等で労災が関係する場合。W-301～W-304も適用候補に追加する。\n業務中・通勤中等で労災が関係する場合。","source":"本人・会社・労働局等","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"交通事故","code":"A-005","title":"交通事故証明書取得用の委任状","purposes":["T5"],"condition":"代理申請の場合。提出先の手続を確認する。","source":"依頼者","target":null,"scope":null,"version":1,"preservation":false},
  {"caseType":"交通事故","code":"A-003","title":"同意書・委任状（医療機関宛て）","purposes":["T5"],"condition":"医療機関、対象期間、同意範囲を確認する。","source":"依頼者等","target":null,"scope":"医療機関、対象期間、同意範囲を確認する。","version":1,"preservation":false},
  {"caseType":"交通事故","code":"A-006","title":"刑事記録閲覧・謄写の申請書・委任関係資料","purposes":["T5"],"condition":"記録の保有先・手続段階に応じて準備する。","source":"事務所・依頼者等","target":null,"scope":"記録の保有先・手続段階。","version":1,"preservation":false},
  {"caseType":"交通事故","code":"A-007","title":"保険会社保有資料の取得用委任状等","purposes":["T5"],"condition":"保険会社・対象資料・権限を確認する。","source":"依頼者","target":null,"scope":"保険会社・対象資料・権限。","version":1,"preservation":false},
  {"caseType":"交通事故","code":"W-301","title":"労災保険給付支給請求書・添付書類","purposes":["T4"],"condition":"業務中・通勤中等で労災が関係する場合。","source":"本人・会社・労基署関係資料","target":null,"scope":"給付種類ごとに管理する。","version":1,"preservation":false},
  {"caseType":"交通事故","code":"W-302","title":"労災給付認定に関する調査復命書・添付資料","purposes":["T4"],"condition":"業務中・通勤中等で労災が関係する場合。","source":"管轄労働局等への開示請求","target":null,"scope":"対象給付・処分を特定する。","version":1,"preservation":false},
  {"caseType":"交通事故","code":"W-303","title":"支給・不支給決定通知","purposes":["T4"],"condition":"業務中・通勤中等で労災が関係する場合。","source":"本人・関係行政機関","target":null,"scope":"決定日・対象給付。","version":1,"preservation":false},
  {"caseType":"交通事故","code":"W-304","title":"支払振込通知・支払証明","purposes":["T4"],"condition":"業務中・通勤中等で労災が関係する場合。","source":"本人・関係行政機関","target":null,"scope":"給付種類・対象期間。","version":1,"preservation":false},
]

